---
title: "Modeling Assignment 2"
author: "Karol Orozco & Charles Hanks" 
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(pROC)
library(MLmetrics)
library(fastDummies)
library(skimr)
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
bank = read_rds("BankChurners.rds") 

bank = bank %>% rename_all(funs(tolower(.))) 

skim(bank)



#EDA on bank 

skim(bank)

bank = bank %>% mutate(churn = as.factor(churn))

#what percentage of customers churn? 
bank %>% group_by(churn) %>% count() %>% mutate(freq = n/nrow(bank))
#16% of customers churn 

bank %>% filter(churn == 1) %>% ggplot(aes(x = credit_limit)) + geom_histogram(bins = 4)
#majority of churners have credit limit under %5000, some are even negative...

bank %>% group_by(churn) %>% summarize(avg_age = mean(customer_age), avg_credit_limit = mean(credit_limit), avg_total_trans_amt = mean(total_trans_amt), avg_util_ratio = mean(avg_utilization_ratio))
#churners average credit utilization ratio is about half of the non churners...they are weening of their credit usage. 

bank %>% ggplot(aes(x = total_trans_amt)) + geom_histogram(aes(fill = churn))
#churners have generally less transaction amount 

bank %>% filter(churn == "yes") %>% ggplot(aes(customer_age))

bank %>% ggplot(aes(x = total_trans_ct)) + geom_histogram(aes(fill=churn))
#most churners have a total_trans_ct less than 50 

variables = bank %>% select(-churn) %>% colnames() 

for(i in variables){
  var = sym(i)
  ggplot(bank,aes(x = !!var)) + geom_histogram(aes(fill = churn))
}

variables[1]
#variables = bank %>% select(-churn) %>% colnames()
#ggplot(bank,aes(x = sym(variables[1]))) + geom_histogram(aes(fill = churn))

bank %>% ggplot(aes(x = months_inactive_12_mon)) + geom_histogram(aes(fill=churn))



```



PCA on bank 
```{r}


bank = bank %>% mutate(churn = as.factor(churn))
bank2 = bank %>% select(-churn) %>% dummy_cols(remove_selected_columns = T)

bank3 = cbind(bank2, select(bank,churn))

pr_bank = prcomp(x = select(bank3,-churn), scale = T, center = T)
summary(pr_bank)

screeplot(pr_bank, type = "lines")
```
```{r}
pr_bank$rotation
```

## Feature Engineering

PCA 

```{r}
rownames_to_column(as.data.frame(pr_bank$rotation)) %>% 
  select(1:5) %>% 
    filter(abs(PC1) >= 0.3 | abs(PC2) >= 0.3 | abs(PC3) >= 0.3 | abs(PC4) >= 0.3)

prc = bind_cols(select(bank3, churn), as.data.frame(pr_bank$x)) %>%
  select(1:5) %>%
    rename("rich_men" = PC1, "cheap_men" = PC2, "young_spenders" = PC3, "old_spenders"= PC4)

#based on the graph below, "young spenders" and "old spenders" seem to be the most impactful of whether they wil churn. 

prc %>%
pivot_longer(cols = -churn, names_to = "component", values_to = "loading") %>% mutate(churn = as.factor(churn)) %>%
ggplot(aes(loading, fill=churn)) +
geom_density(alpha = 0.5) +
facet_grid(.~component)


```

```{r}
#choosing "old_spenders" and "young_spenders" to be 2 of the 5 total features in the model: 
prc2 = prc %>% select(young_spenders,old_spenders) 

#combining these features with rest of bank ds, then grabbing 3 promising variables: 
banksy = cbind(prc2, bank3) %>% 
            select(young_spenders, old_spenders,credit_limit,total_trans_amt,avg_utilization_ratio, churn)

banksy = banksy %>% mutate(log_credit_limit = log(credit_limit)) %>% select(-credit_limit)

ggplot(banksy, aes(x = log_credit_limit)) + geom_histogram()

```


## Specification: knn model 

```{r}
# specify the model to be used (i.e. KNN, Naive Bayes, decision tree, random forest, bagged trees) and the tuning parameters used

ctrl <- trainControl(method = "cv", number = 3, classProbs=TRUE, summaryFunction = twoClassSummary)

set.seed(504) 

bank_index <- createDataPartition(banksy$churn, p = 0.80, list = FALSE)
train <- banksy[ bank_index, ]
test <- banksy[-bank_index, ]

# example spec for rf
fit <- train(churn ~ .,
             data = train, 
             method = "knn",
             preProcess = c("center","scale"),
             tuneGrid = expand.grid(k = seq(31,41,2)),
             metric = "ROC",
             trControl = ctrl)

fit

confusionMatrix(predict(fit, test),factor(test$churn))

myRoc <- roc(test$churn, predict(fit, test, type="prob")[,2])

plot(myRoc)
auc(myRoc)

```
## Downsampling bank data to remove imbalance of yes/no churn: 

```{r}
traindown = downSample(x = train[,-5], y= train$churn) %>% mutate(churn = Class) %>% select(-Class)


traindown %>% group_by(churn) %>% count()
```
## Random Forest Model

```{r}
fit <- train(churn ~ .,
             data = traindown, 
             method = "rf",
             tuneLength = 4, 
             metric = "ROC",
             trControl = ctrl)

confusionMatrix(predict(fit, test),factor(test$churn))

myRoc <- roc(test$churn, predict(fit, test, type="prob")[,2])

plot(myRoc)
auc(myRoc) 

```


## Best model

```{r}
# Here are a few lines to inspect your best model. Add some comments about optimal hyperparameters.
print(fit)
print(fit$bestTune)
```


## Re-fit and evaluation

```{r}
# the "method" below should match the one you chose above. 

set.seed(1504) # I will choose a different seed for evaluation

bank_index <- createDataPartition(banksy$churn, p = 0.80, list = FALSE)
train <- banksy[ bank_index, ]
test <- banksy[-bank_index, ]

# example spec for rf
fit_final <- train(churn ~ .,
             data = train, 
             method = "rf",
             tuneGrid=fit$bestTune,
             metric = "ROC",
             trControl = ctrl) 
# The last line means we will fit a model using the best tune parameters your CV found above.

myRoc <- roc(test$churn, predict(fit_final, test, type="prob")[,2])

plot(myRoc)
auc(myRoc)
```

